config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  resources :jets

  authenticated :user do
    root :to => 'jets#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/jet.rb
class Jet < ActiveRecord::Base
  attr_accessible :content, :user_id
  validates :content, :presence => true,
                      :length => { :maximum => 140 }

  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
	rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  validates :name, :presence => true,
                   :uniqueness => true
  has_many :jets
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/jets_controller.rb
class JetsController < ApplicationController
  # GET /jets
  # GET /jets.json
  def index
    @jets = Jet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jets }
    end
  end

  # GET /jets/1
  # GET /jets/1.json
  def show
    @jet = Jet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @jet }
    end
  end

  # GET /jets/new
  # GET /jets/new.json
  def new
    @jet = Jet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @jet }
    end
  end

  # GET /jets/1/edit
  def edit
    @jet = Jet.find(params[:id])
  end

  # POST /jets
  # POST /jets.json
  def create
    @jet = Jet.new(params[:jet])
    @jet.user_id = current_user.id

    respond_to do |format|
      if @jet.save
        @jets = Jet.all
        format.html { redirect_to jets_path, notice: 'Jet was successfully created.' }
        format.json { render json: @jets, status: :created, location: @jet }
      else
        format.html { render action: "new" }
        format.json { render json: @jet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jets/1
  # PUT /jets/1.json
  def update
    @jet = Jet.find(params[:id])

    respond_to do |format|
      if @jet.update_attributes(params[:jet])
        format.html { redirect_to @jet, notice: 'Jet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @jet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jets/1
  # DELETE /jets/1.json
  def destroy
    @jet = Jet.find(params[:id])
    @jet.destroy

    respond_to do |format|
      format.html { redirect_to jets_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html { redirect_to "/jets" }
      format.json { render json: @user }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jets_helper.rb
module JetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Let your world fly on jet!</h1><br/><br/><h3>Please login to take off</h3><br/><br/>

app/views/jets/_form.html.erb
<html>
  <head>
 <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
		
</head>
<body>
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
	<div class="nav-collapse">
            <ul class="nav">
              <%= render 'layouts/navigation' %>
              </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
<%= form_for(@jet) do |f| %>
  <% if @jet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jet.errors.count, "error") %> prohibited this jet from being saved:</h2>

      <ul>
      <% @jet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :user_id, :value => current_user.id, :class => "invisible_textbox" %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
</body>
</html>

app/views/jets/edit.html.erb
<h1>Editing jet</h1>

<%= render 'form' %>

<%= link_to 'Show', @jet %> |
<%= link_to 'Back', jets_path %>

app/views/jets/index.html.erb
<html>
<head>
</head>
<body>
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <div class="nav-collapse">
            <ul class="nav">
              <%= render 'layouts/navigation' %>
              </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
<div class="">
<h1>Your timeline!</h1>

<br />
<%= link_to 'Drive new jet', new_jet_path %><br/><br/>
<%
def getUserName(id)
  user = User.find_by_id(id)
  return user.name
end
%>
<% @jets.each do |jet| %>
<% if jet.user_id == current_user.id %>
<div class="hero-unit">
  Jet driven by <b><%= getUserName(jet.user_id) %></b> <%= jet.created_at.strftime(" on %B %d, %Y at %I:%M %p") %><br/>
    <%= jet.content %><br/><br/>
    
    <%= link_to 'Delete jet', jet, confirm: 'Are you sure?', method: :delete %></div>
<% end %>
<% end %>

<br />


</body>
</html>

app/views/jets/new.html.erb
<h1>New jet</h1>

<%= render 'form' %>

<%= link_to 'Back', jets_path %>

app/views/jets/show.html.erb
<html>
<head>
</head>
<body>
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <div class="nav-collapse">
            <ul class="nav">
              <%= render 'layouts/navigation' %>
              </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
<div class="container">

<p>
  <b>Userid:</b>
  <%= @jet.user_id %>
</p>

<p>
  <b>Content:</b>
  <%= @jet.content %>
</p>


<%= link_to 'Edit', edit_jet_path(@jet) %> |
<%= link_to 'Back', jets_path %>
</div>
</body>
</html>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to image_tag("logo.png", :border => 0), root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to('Admin', users_path) %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Jetter" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <%= yield(:head) %>
  </head>
  <body>
    <span style="position:absolute;left:210px;">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <br/>
        <div class="">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
    </div> <!--! end of #main -->
    </span>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>